spring:
  application:
    name: sboot-virtual-card-management
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  sql:
    init:
      mode: always

app:
  credit:
    min-limit: 250
    max-limit: 10000
  card:
    number-prefix: 8080
    expiration-offset: 6
  hash:
    algorithm: SHA3-256
  encryption:
    algorithm: AES
    secret-key: 123456789


server:
  port: 8080